[2025-02-24T05:05:30.404+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T05:05:30.430+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_1.second_task scheduled__2025-02-21T00:00:00+00:00 [queued]>
[2025-02-24T05:05:30.439+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_1.second_task scheduled__2025-02-21T00:00:00+00:00 [queued]>
[2025-02-24T05:05:30.440+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T05:05:30.465+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-21 00:00:00+00:00
[2025-02-24T05:05:30.472+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T05:05:30.474+0000] {standard_task_runner.py:72} INFO - Started process 2245 to run task
[2025-02-24T05:05:30.472+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_1', 'second_task', 'scheduled__2025-02-21T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpnowxc9zk']
[2025-02-24T05:05:30.475+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask second_task
[2025-02-24T05:05:30.518+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_1.second_task scheduled__2025-02-21T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T05:05:30.610+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag_1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-21T00:00:00+00:00'
[2025-02-24T05:05:30.611+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T05:05:30.627+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T05:05:30.628+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-24T05:05:30.638+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T05:05:30.640+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-24T05:05:30.641+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T05:05:30.670+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T05:05:30.671+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag_1, task_id=second_task, run_id=scheduled__2025-02-21T00:00:00+00:00, execution_date=20250221T000000, start_date=20250224T050530, end_date=20250224T050530
[2025-02-24T05:05:30.729+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T05:05:30.767+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T05:05:30.770+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
