[2025-02-24T05:05:27.929+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T05:05:27.962+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_1.first_task scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-24T05:05:27.980+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_1.first_task scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-24T05:05:27.982+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T05:05:28.001+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-17 00:00:00+00:00
[2025-02-24T05:05:28.009+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T05:05:28.009+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_1', 'first_task', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmp4gnp8_56']
[2025-02-24T05:05:28.010+0000] {standard_task_runner.py:72} INFO - Started process 2197 to run task
[2025-02-24T05:05:28.011+0000] {standard_task_runner.py:105} INFO - Job 219: Subtask first_task
[2025-02-24T05:05:28.088+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_1.first_task scheduled__2025-02-17T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T05:05:28.245+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag_1' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-24T05:05:28.254+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T05:05:28.271+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T05:05:28.273+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-24T05:05:28.282+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T05:05:28.283+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-24T05:05:28.284+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T05:05:28.309+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T05:05:28.310+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag_1, task_id=first_task, run_id=scheduled__2025-02-17T00:00:00+00:00, execution_date=20250217T000000, start_date=20250224T050527, end_date=20250224T050528
[2025-02-24T05:05:28.348+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T05:05:28.395+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-24T05:05:28.397+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
