[2025-02-23T15:52:42.761+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:42.777+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-23T15:52:42.787+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-23T15:52:42.789+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:42.805+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-17 00:00:00+00:00
[2025-02-23T15:52:42.813+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'first_task', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpvqmg9asj']
[2025-02-23T15:52:42.814+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1538) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:42.816+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask first_task
[2025-02-23T15:52:42.816+0000] {standard_task_runner.py:72} INFO - Started process 1541 to run task
[2025-02-23T15:52:42.870+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.first_task scheduled__2025-02-17T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:42.976+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-23T15:52:42.977+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:42.999+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:43.000+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-23T15:52:43.010+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:43.012+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-23T15:52:43.013+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:43.043+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:43.044+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=first_task, run_id=scheduled__2025-02-17T00:00:00+00:00, execution_date=20250217T000000, start_date=20250223T155242, end_date=20250223T155243
[2025-02-23T15:52:43.157+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:43.192+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:43.196+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:20.537+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:20.553+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-24T04:47:20.562+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-24T04:47:20.563+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:20.575+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-17 00:00:00+00:00
[2025-02-24T04:47:20.583+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1086) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:20.582+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'first_task', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmphj483leu']
[2025-02-24T04:47:20.584+0000] {standard_task_runner.py:72} INFO - Started process 1087 to run task
[2025-02-24T04:47:20.585+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask first_task
[2025-02-24T04:47:20.631+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.first_task scheduled__2025-02-17T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:20.709+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-24T04:47:20.711+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:20.723+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:20.724+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-24T04:47:20.734+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:20.736+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-24T04:47:20.737+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:20.758+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:20.761+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=first_task, run_id=scheduled__2025-02-17T00:00:00+00:00, execution_date=20250217T000000, start_date=20250224T044720, end_date=20250224T044720
[2025-02-24T04:47:20.800+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:20.833+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:20.836+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
