[2025-02-23T15:52:37.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T15:52:38.006+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-23T15:52:38.027+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-23T15:52:38.028+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T15:52:38.062+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-14 00:00:00+00:00
[2025-02-23T15:52:38.077+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1417) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T15:52:38.080+0000] {standard_task_runner.py:72} INFO - Started process 1438 to run task
[2025-02-23T15:52:38.083+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'first_task', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpi665y7sw']
[2025-02-23T15:52:38.090+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask first_task
[2025-02-23T15:52:38.175+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.first_task scheduled__2025-02-14T00:00:00+00:00 [running]> on host 2cebbf768e94
[2025-02-23T15:52:38.285+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-23T15:52:38.286+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T15:52:38.313+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T15:52:38.315+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-23T15:52:38.332+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T15:52:38.334+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-23T15:52:38.337+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T15:52:38.396+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T15:52:38.397+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=first_task, run_id=scheduled__2025-02-14T00:00:00+00:00, execution_date=20250214T000000, start_date=20250223T155238, end_date=20250223T155238
[2025-02-23T15:52:38.582+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T15:52:38.636+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T15:52:38.641+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T04:47:15.048+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:15.093+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-24T04:47:15.106+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.first_task scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-24T04:47:15.106+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:15.128+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-14 00:00:00+00:00
[2025-02-24T04:47:15.138+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=907) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:15.140+0000] {standard_task_runner.py:72} INFO - Started process 933 to run task
[2025-02-24T04:47:15.144+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'first_task', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpvrfquc40']
[2025-02-24T04:47:15.151+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask first_task
[2025-02-24T04:47:15.256+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.first_task scheduled__2025-02-14T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:15.440+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-24T04:47:15.441+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:15.478+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T04:47:15.480+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world! the first task is defined!!!']
[2025-02-24T04:47:15.505+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T04:47:15.507+0000] {subprocess.py:106} INFO - hello world! the first task is defined!!!
[2025-02-24T04:47:15.510+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T04:47:15.565+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:15.566+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=first_task, run_id=scheduled__2025-02-14T00:00:00+00:00, execution_date=20250214T000000, start_date=20250224T044715, end_date=20250224T044715
[2025-02-24T04:47:15.647+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:15.721+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:15.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
