[2025-02-24T05:05:21.802+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T05:05:21.830+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_1.second_task scheduled__2025-02-15T00:00:00+00:00 [queued]>
[2025-02-24T05:05:21.845+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_1.second_task scheduled__2025-02-15T00:00:00+00:00 [queued]>
[2025-02-24T05:05:21.848+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T05:05:21.871+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-02-15 00:00:00+00:00
[2025-02-24T05:05:21.883+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2034) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T05:05:21.885+0000] {standard_task_runner.py:72} INFO - Started process 2050 to run task
[2025-02-24T05:05:21.884+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_1', 'second_task', 'scheduled__2025-02-15T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmp8kzdaiy0']
[2025-02-24T05:05:21.889+0000] {standard_task_runner.py:105} INFO - Job 176: Subtask second_task
[2025-02-24T05:05:21.977+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_1.second_task scheduled__2025-02-15T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T05:05:22.131+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag_1' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T00:00:00+00:00'
[2025-02-24T05:05:22.133+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T05:05:22.151+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T05:05:22.154+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is task 2, and will be run after task 1.']
[2025-02-24T05:05:22.172+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T05:05:22.173+0000] {subprocess.py:106} INFO - hey, this is task 2, and will be run after task 1.
[2025-02-24T05:05:22.174+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T05:05:22.205+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T05:05:22.206+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag_1, task_id=second_task, run_id=scheduled__2025-02-15T00:00:00+00:00, execution_date=20250215T000000, start_date=20250224T050521, end_date=20250224T050522
[2025-02-24T05:05:22.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T05:05:22.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
