[2025-02-24T05:05:21.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T05:05:21.117+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_1.third_task scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-24T05:05:21.157+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_1.third_task scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-24T05:05:21.158+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T05:05:21.191+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-02-10 00:00:00+00:00
[2025-02-24T05:05:21.201+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_1', 'third_task', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpfz21qvhf']
[2025-02-24T05:05:21.211+0000] {standard_task_runner.py:105} INFO - Job 168: Subtask third_task
[2025-02-24T05:05:21.208+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2003) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T05:05:21.214+0000] {standard_task_runner.py:72} INFO - Started process 2027 to run task
[2025-02-24T05:05:21.334+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_1.third_task scheduled__2025-02-10T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T05:05:21.480+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag_1' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T00:00:00+00:00'
[2025-02-24T05:05:21.482+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T05:05:21.510+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T05:05:21.512+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo finally, it will be done!!!']
[2025-02-24T05:05:21.530+0000] {subprocess.py:99} INFO - Output:
[2025-02-24T05:05:21.533+0000] {subprocess.py:106} INFO - finally, it will be done!!!
[2025-02-24T05:05:21.535+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-24T05:05:21.584+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T05:05:21.585+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag_1, task_id=third_task, run_id=scheduled__2025-02-10T00:00:00+00:00, execution_date=20250210T000000, start_date=20250224T050521, end_date=20250224T050521
[2025-02-24T05:05:21.891+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T05:05:21.950+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-24T05:05:21.959+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
