[2025-02-24T04:47:15.979+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T04:47:16.012+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.great_func scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-24T04:47:16.029+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.great_func scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-24T04:47:16.030+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-24T04:47:16.066+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): great_func> on 2025-02-02 00:00:00+00:00
[2025-02-24T04:47:16.083+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'great_func', 'scheduled__2025-02-02T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpchki5662']
[2025-02-24T04:47:16.086+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask great_func
[2025-02-24T04:47:16.084+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=969) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-24T04:47:16.092+0000] {standard_task_runner.py:72} INFO - Started process 983 to run task
[2025-02-24T04:47:16.204+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.great_func scheduled__2025-02-02T00:00:00+00:00 [running]> on host 79e0cb3ed452
[2025-02-24T04:47:16.327+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gzang' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='great_func' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T00:00:00+00:00'
[2025-02-24T04:47:16.331+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T04:47:16.370+0000] {logging_mixin.py:190} INFO - *** chào Thùy, i am 1 days old!!!
[2025-02-24T04:47:16.373+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-24T04:47:16.391+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T04:47:16.392+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=great_func, run_id=scheduled__2025-02-02T00:00:00+00:00, execution_date=20250202T000000, start_date=20250224T044716, end_date=20250224T044716
[2025-02-24T04:47:16.645+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-24T04:47:16.690+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-24T04:47:16.709+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
